# Changes here will be overwritten by Copier
_commit: v0.10.0
_src_path: gh:bhklab/bhklab-project-template
author_email: bhklab.jermiahjoseph@gmail.com
author_full_name: Jermiah Joseph
github_username: jjjermiah
has_additional_authors: false
project_description: GDSC 1 and 2 into treatmentResponseExperiments
project_name: GDSC TreatmentResponse Snakemake
project_slug: gdsc-treatmentresponse-snakemake
publish_to_github: true
python_version: '3.12'
repo_location: BHKLAB-DataProcessing
